### ISSUE TITLE
非swoft框架调用RPC文档没有写清楚

### ISSUE THREAD

**Issue by allenliao123** [swoft-cloud/swoft-doc#104]
### 2.X非框架的RPC调用的文档木有写清楚
> 文档2.X希望能增加一下

**Comment by minbaby** [comment]
刚刚提了一个PR #117 ，可以参考一下，也可以看看[swoft-rpc-client](https://github.com/minbaby/swoft-rpc-client), 这个是我从框架里扣出来了，封装了一下。

**Comment by inhere** [comment]
已合并
