### ISSUE TITLE
非Swoft调用RPC客户端文档有些问题

### ISSUE THREAD

**Issue by tangxunye** [swoft-cloud/swoft-doc#151]
while (!feof($fp)) {
        $tmp = stream_socket_recvfrom($fp, 1024);
        if (strpos($tmp, RPC_EOL)) {
            #缺少赋值语句
            $result .= $tmp;
            #
            break;
        } else {
            $result .= $tmp;
        }
    }

**Comment by inhere** [comment]
嗯 发现问题可以直接修改

**Comment by inhere** [comment]
已经修复了
