### ISSUE TITLE
using jmeter test redis, when send 50 threads,

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft-doc#41]
{"msg":"Connection pool waiting queue is full, maxActive=8,maxWait=8,currentCount=9","file":"\/var\/www\/swoft\/vendor\/swoft\/framework\/src\/Pool\/ConnectionPool.php","line":240,"code":0}

**Comment by wujunze** [comment]
please move isssue to https://github.com/swoft-cloud/swoft/

**Comment by huangzhhui** [comment]
扩大自己的Redis连接池配置即可
