### ISSUE TITLE
内置的redis类，hgetall\hmset等命令的问题

### ISSUE THREAD

**Issue by allovine** [swoft-cloud/swoft-doc#49]
hgetall 返回的不是key=>value的形式，而是把所有的 key\value 都放到了数组里面

set\hmset\hset 时候，如果是整形的，设置完之后无法 hincrby 或者 incrby ，提示不是一个整形数字

例如如下代码：
        $rd2 = new \Redis();
        $rd2->connect("127.0.0.1",6379);
        $rd2->select(6);
       $rd2->hMset('myms3', array('name' => 'Joe', 'salary' => 2000));

        $this->gameRedis->hMset('myms1', array('name' => 'Joe', 'salary' => 2000));
        $this->gameRedis->hSet("myms1","d",4);
        

用原装的redis类执行后和内置的redis执行后，redis-cli 看到的是如图：
127.0.0.1:6379[6]> hgetall myms1
1) "name"
2) "s:3:\"Joe\";"
3) "salary"
4) "i:2000;"
5) "d"
6) "i:4;"
127.0.0.1:6379[6]> hgetall myms3
1) "name"
2) "Joe"
3) "salary"
4) "2000"
5) "salery"
6) "111"

而 myms1 是无法用 hincrby myms1 salary 1 的命令的，会提示 salary 不是整形

hgetall的问题，处理的时候就是不用 hgetall ，改用 hmget 就没事儿，但是 hmset 的int型字段实在没办法了。紧急求助！！！！！难道要抛弃内置的redis，采用原装的\Redis，自己再链接？

**Comment by huangzhhui** [comment]
ref https://github.com/swoft-cloud/swoft/issues/337
