### ISSUE TITLE
中间件配置问题

### ISSUE THREAD

**Issue by back0893** [swoft-cloud/swoft-doc#62]
使用rpc服务伴随http启动的问题
当依据 文档是上添加
 'class'=>\Swoft\Rpc\Server\ServiceDispatcher::class
会出现访问http服务器被ServiceDispatcher拦截
会走到 /swoft/rpc-server/src/ServiceDispatcher.php的72行导致请求中断
不添加拦截器后http访问成功,rpc服务正常运行

**Comment by huangzhhui** [comment]
无需自行配置，该配置由 rpc-server 的 corebean 实现配置，已去除文档对应部分的内容
