### ISSUE TITLE
docker安装成功之后无法访问问题

### ISSUE THREAD

**Issue by qiaohengshan** [swoft-cloud/swoft-doc#72]
Case 1:
docker run -d -p 80:80  --name swoft  swoft/swoft
这样安装宿主机可以正常访问，本机localhost却无法访问
Case 2:
docker run -d -p 80:80 -v /e/www/swoft:/var/www/swoft  --name swoft  swoft/swoft
将本地项目和宿主关联上之后，宿主机无法访问，本地localhost也无法访问

**Comment by wujunze** [comment]
请到 https://github.com/swoft-cloud/swoft/issues  这里统一提交 issue
