### ISSUE TITLE
swoft2数据库value方法查询下划线字段问题

### ISSUE THREAD

**Issue by dongqibin** [swoft-cloud/swoft-doc#77]
当表字段为下划线分割的字段(time_create)时候.
在使用value方法时.如果传入time_create.则会提示time_create字段不存在.因为value方法内部调用了first方法.而first方法返回的字段属性名称为驼峰法.
而如果传入timeCreate时候.在查询阶段就会报错.因为表字段为time_create而非timeCreate.
建议value方法返回的时候.将传入的下划线分割的字段改为通过类似getTimeCreate()的方法获取.或者使用->timeCreate属性获取.

**Comment by dongqibin** [comment]
指定版本

**Comment by sakuraovq** [comment]
@dongqibin  是使用实体的bug是吧 我们改下哈

**Comment by sakuraovq** [comment]
@dongqibin  更新下最新master 代码  传入的字段名 统一为 真实的字段名。 谢谢您的反馈
